/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author eu
 */
public class TelaPopupMenu extends javax.swing.JFrame {

    /**
     * Creates new form TelaPopupMenu
     */
    public TelaPopupMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPop = new javax.swing.JPopupMenu();
        itRec = new javax.swing.JMenuItem();
        itCop = new javax.swing.JMenuItem();
        itCol = new javax.swing.JMenuItem();
        itExcl = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itSel = new javax.swing.JMenuItem();
        txtMens = new javax.swing.JTextField();

        itRec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itRec.setText("Recortar");
        itRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itRecActionPerformed(evt);
            }
        });
        menuPop.add(itRec);

        itCop.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itCop.setText("Copiar");
        itCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itCopActionPerformed(evt);
            }
        });
        menuPop.add(itCop);

        itCol.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itCol.setText("Colar");
        itCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itColActionPerformed(evt);
            }
        });
        menuPop.add(itCol);

        itExcl.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        itExcl.setText("Excluir");
        itExcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itExclActionPerformed(evt);
            }
        });
        menuPop.add(itExcl);
        menuPop.add(jSeparator1);

        itSel.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itSel.setText("Selecionar Tudo");
        itSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSelActionPerformed(evt);
            }
        });
        menuPop.add(itSel);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Popup");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.png")).getImage());
        setResizable(false);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                formMouseReleased(evt);
            }
        });

        txtMens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtMensMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(txtMens, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(txtMens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseReleased
        
    }//GEN-LAST:event_formMouseReleased

    private void txtMensMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMensMouseReleased
        if(evt.isPopupTrigger()) {
            menuPop.show(txtMens, 200, evt.getY());
        }
    }//GEN-LAST:event_txtMensMouseReleased

    private void itRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itRecActionPerformed
        txtMens.cut();
    }//GEN-LAST:event_itRecActionPerformed

    private void itCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itCopActionPerformed
        txtMens.copy();
    }//GEN-LAST:event_itCopActionPerformed

    private void itColActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itColActionPerformed
        txtMens.paste();
    }//GEN-LAST:event_itColActionPerformed

    private void itExclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itExclActionPerformed
        try {
            String texto = txtMens.getSelectedText();
            
            String recorte = txtMens.getText().replace(texto, "");
            
            txtMens.setText(recorte);
        }
        catch(NullPointerException ex) {
            
        }
    }//GEN-LAST:event_itExclActionPerformed

    private void itSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSelActionPerformed
        txtMens.grabFocus();
        
        txtMens.selectAll();
    }//GEN-LAST:event_itSelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPopupMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPopupMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itCol;
    private javax.swing.JMenuItem itCop;
    private javax.swing.JMenuItem itExcl;
    private javax.swing.JMenuItem itRec;
    private javax.swing.JMenuItem itSel;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu menuPop;
    private javax.swing.JTextField txtMens;
    // End of variables declaration//GEN-END:variables
}
